### ISSUE TITLE
Missing libgomp dependency in gromacs container

### ISSUE THREAD

**Issue by samcmill** [autamus/registry#368]
The Gromacs container does not include all its dependencies.  It is missing libgomp.so.1.

```
$ docker run --rm -it ghcr.io/autamus/gromacs:latest gmx_mpi
gmx_mpi: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
```

```
$ docker run --rm -it --entrypoint bash ghcr.io/autamus/gromacs:latest
root@b045ae42c1de:/# ldd /opt/view/bin/gmx_mpi
...
	libgomp.so.1 => not found
...
root@b045ae42c1de:/# ldconfig -p | grep libgomp
root@b045ae42c1de:/# find / -name libgomp.so.1 -print
find: '/proc/1/map_files': Operation not permitted
find: '/proc/19/map_files': Operation not permitted
root@b045ae42c1de:/#
```

**Comment by alecbcs** [comment]
@samcmill good catch! It looks like Spack isn't able to build `libgomp` so we'll have to bootstrap the build off of the Ubuntu archives for the moment. Hopefully #369 fixes this issue. I'll update the status here after the build finishes and then if the new container passes your tests feel free to close the issue. If not maybe we'll have to do a little more work.

**Comment by alecbcs** [comment]
@samcmill the gromacs container should be all rebuilt and ready to go. Let me know if it passes your test cases now!

**Comment by alecbcs** [comment]
@samcmill I'm going to go ahead and close this issue since gromacs seems to be passing all of my tests now. If anything isn't working for you I'm happy to reopen.
