### ISSUE TITLE
Reporting Broken Packages (Discussion)

### ISSUE THREAD

**Issue by vsoch** [autamus/registry#78]
I was looking for clingo-bootstrap and didn't see it here: https://github.com/autamus/registry/actions/runs/653446886 so I doubled back, and indeed we had a merged PR that shows deploying the container: https://github.com/autamus/registry/runs/2110767149?check_suite_focus=true. But it's not there! I wonder if GitHub packages is somehow buggy / doesn't show all the containers? Or it has incorrect permissions?

```bash
$ docker pull ghcr.io/autamus/clingo-bootstrap:latest
Error response from daemon: Head https://ghcr.io/v2/autamus/clingo-bootstrap/manifests/latest: unauthorized
```
In terms of multi-arch (I think we were talking about this) I don't think it's supported - https://github.community/t/package-details-and-manifest-are-missing/136818. That could be a reason, but I didn't think we were building anything significantly different yet. Let me know if we should open an issue with GitHub.

**Comment by alecbcs** [comment]
![image](https://user-images.githubusercontent.com/19558067/111182366-14fcb500-856c-11eb-99e7-c7b9392415a3.png)

@vsoch Hahaha the issue you ran into was that I slept in this morning lol. So unfortunately by default whenever a new container is created on GHCR it's initially set to private and we've got to go change the visibility settings to public. I'd love to automate this but I haven't seen a way how to yet.  Until then let me see if I can't make you an admin/give you access to see and make private packages public.

**Comment by vsoch** [comment]
Oh I didn't know that! I don't see it exposed in their APIs either. I'll ask on Twitter if they have plans to add that - it definitely would be useful for us.

**Comment by alecbcs** [comment]
Okay you should have full access now. Let me know if you still can't see and update private packages.

**Comment by vsoch** [comment]
Got it! And I posted on Twitter. This is neat - it looks like you can associate a package with a repository, and even give other users maintainer permission. That could come in handy!

**Comment by vsoch** [comment]
Are you still hitting bugs every now and then with adding packages, or is this something we could automate too?

**Comment by alecbcs** [comment]
We could probably automate the process of pulling package specs from the Spack Repo. I've just been doing it manually based off of the `module avail` output of our HPC clusters to get an initial set of commonly used analysis packages. I guess the only worry automating the entire process might be hitting some GitHub anti-spam protections if we create too many PRs to quickly.

**Comment by alecbcs** [comment]
Other than packaging issues from within Spack builds tho everything looks to be operating well.

**Comment by vsoch** [comment]
Gotcha! So maybe the manual approach is okay for now then. It would be pretty funny to see GitHub packages break, but I definitely don't want to trigger some kind of anti-spam protection.

**Comment by alecbcs** [comment]
@vsoch haha agreed. Feel free to keep adding any packages you can think of tho! If it's of interest I can probably script something that'll automatically copy/create the include branch for a piece of software based on the name of the package directory in the Spack Repository. Maybe something like...

```bash
#!/bin/bash
git checkout main
git checkout -b include-$2
cp -r $1/$2 spack/${$2::1}/$2
git push -u origin include-$2
git checkout main
```

Which could be used like `./script /path/to/spack/repo/var/spack/repos/builtin/packages package-name`

**Comment by vsoch** [comment]
Are we keeping track of which packages don't build (and it's a bug with the package itself?) I remember you opened an issue for axom, but if we hit any others, you can ping me and I'd be happy to open the issue! I can understand maintainers not wanting to be bombarded with package update PRs, but if a current package version doesn't build, we should let them know about it.

I don't have any packages I need imminently, but if/when I do I'll definitely add here so I don't need to actually install :) Do we have a plan for a next step once we have a bunch of containers? Are you going to try advertising to use them from your cluster?

**Comment by alecbcs** [comment]
> Are we keeping track of which packages don't build (and it's a bug with the package itself?) I remember you opened an issue for axom, but if we hit any others, you can ping me and I'd be happy to open the issue! I can understand maintainers not wanting to be bombarded with package update PRs, but if a current package version doesn't build, we should let them know about it.

Sure! Except for Amber, I believe all of the other failing PRs are problems with the spack packages themselves. I started to work on fixing Augustus but then I ran out of time between lab work (this) and homework. Generally if the builds don't fail in the first two stages then it's a missing dependency or something wrong with the Spack build. I'll probably take some time this weekend to open issues for them this weekend but if you've got some time before then opening some issues would be great!

> I don't have any packages I need imminently, but if/when I do I'll definitely add here so I don't need to actually install :) Do we have a plan for a next step once we have a bunch of containers? Are you going to try advertising to use them from your cluster?

Yeah totally! I've already started reaching out to other programmers at UA and NAU to see if they'd be interested trying out the containers but once we've got more options I think you're totally right that's the next step.

**Comment by vsoch** [comment]
Do you want to make a label like `package-label` and apply it these packages and then I can easily help (minimally opening an issue)?

**Comment by alecbcs** [comment]
Sure!
